repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0
    hooks:
      - id: prettier
        files: ^frontend/(src|tests)/.*\.(ts|tsx|css)$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--config-file", "pyproject.toml"]
        files: "^(src|scripts)/"
  - repo: local
    hooks:
      - id: frontend-lint
        name: frontend eslint
        entry: npm
        language: system
        args: ["--prefix", "frontend", "run", "lint"]
        pass_filenames: false
        types_or: [ts, tsx]
        files: ^frontend/(src|tests)/
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
