name: Auto Format Fixes

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  black-auto-format:
    name: Apply Black formatting
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black==24.4.2

      - name: Run Black formatter
        run: black .

      - name: Commit formatted changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply black formatting"
          branch: ${{ github.head_ref }}
          commit_options: '--no-verify'


